// All service slugs
export const serviceSlugs = [
  'digital-marketing',
  'advertising',
  'branding',
  'website-development',
  'software-development',
  'graphic-design',
  'media-production',
  'public-relations',
  'political-campaigns',
  'ooh-advertising',
  'radio-newspapers',
  'product-marketing',
];

// All industry slugs
export const industrySlugs = [
  'healthcare',
  'education',
  'real-estate',
  'ecommerce',
  'technology',
  'finance',
  'hospitality',
  'automotive',
  'fashion',
  'legal',
  'manufacturing',
  'agriculture',
  'logistics',
  'construction',
  'retail',
  'energy',
  'non-profit',
  'sports-fitness',
];

// All blog slugs (224 total)
export const blogSlugs = [
  // SEO & Local SEO (1-24)
  'best-seo-company-indore-2025',
  'local-seo-small-business-indore',
  'seo-topic-3',
  'seo-topic-4',
  'seo-topic-5',
  'seo-topic-6',
  'seo-topic-7',
  'seo-topic-8',
  'seo-topic-9',
  'seo-topic-10',
  'seo-topic-11',
  'seo-topic-12',
  'seo-topic-13',
  'seo-topic-14',
  'seo-topic-15',
  'seo-topic-16',
  'seo-topic-17',
  'seo-topic-18',
  'seo-topic-19',
  'seo-topic-20',
  'seo-topic-21',
  'seo-topic-22',
  'seo-topic-23',
  'seo-topic-24',
  
  // PPC & Google Ads (25-48)
  'ppc-topic-25',
  'ppc-topic-26',
  'ppc-topic-27',
  'ppc-topic-28',
  'ppc-topic-29',
  'ppc-topic-30',
  'ppc-topic-31',
  'ppc-topic-32',
  'ppc-topic-33',
  'ppc-topic-34',
  'ppc-topic-35',
  'ppc-topic-36',
  'ppc-topic-37',
  'ppc-topic-38',
  'ppc-topic-39',
  'ppc-topic-40',
  'ppc-topic-41',
  'ppc-topic-42',
  'ppc-topic-43',
  'ppc-topic-44',
  'ppc-topic-45',
  'ppc-topic-46',
  'ppc-topic-47',
  'ppc-topic-48',
  
  // Social Media Marketing (49-72)
  'social-media-topic-49',
  'social-media-topic-50',
  'social-media-topic-51',
  'social-media-topic-52',
  'social-media-topic-53',
  'social-media-topic-54',
  'social-media-topic-55',
  'social-media-topic-56',
  'social-media-topic-57',
  'social-media-topic-58',
  'social-media-topic-59',
  'social-media-topic-60',
  'social-media-topic-61',
  'social-media-topic-62',
  'social-media-topic-63',
  'social-media-topic-64',
  'social-media-topic-65',
  'social-media-topic-66',
  'social-media-topic-67',
  'social-media-topic-68',
  'social-media-topic-69',
  'social-media-topic-70',
  'social-media-topic-71',
  'social-media-topic-72',
  
  // Content Marketing & Blogging (73-96)
  'content-marketing-topic-73',
  'content-marketing-topic-74',
  'content-marketing-topic-75',
  'content-marketing-topic-76',
  'content-marketing-topic-77',
  'content-marketing-topic-78',
  'content-marketing-topic-79',
  'content-marketing-topic-80',
  'content-marketing-topic-81',
  'content-marketing-topic-82',
  'content-marketing-topic-83',
  'content-marketing-topic-84',
  'content-marketing-topic-85',
  'content-marketing-topic-86',
  'content-marketing-topic-87',
  'content-marketing-topic-88',
  'content-marketing-topic-89',
  'content-marketing-topic-90',
  'content-marketing-topic-91',
  'content-marketing-topic-92',
  'content-marketing-topic-93',
  'content-marketing-topic-94',
  'content-marketing-topic-95',
  'content-marketing-topic-96',
  
  // Web Design & Development (97-120)
  'web-design-topic-97',
  'web-design-topic-98',
  'web-design-topic-99',
  'web-design-topic-100',
  'web-design-topic-101',
  'web-design-topic-102',
  'web-design-topic-103',
  'web-design-topic-104',
  'web-design-topic-105',
  'web-design-topic-106',
  'web-design-topic-107',
  'web-design-topic-108',
  'web-design-topic-109',
  'web-design-topic-110',
  'web-design-topic-111',
  'web-design-topic-112',
  'web-design-topic-113',
  'web-design-topic-114',
  'web-design-topic-115',
  'web-design-topic-116',
  'web-design-topic-117',
  'web-design-topic-118',
  'web-design-topic-119',
  'web-design-topic-120',
  
  // Branding & Design (121-144)
  'branding-topic-121',
  'branding-topic-122',
  'branding-topic-123',
  'branding-topic-124',
  'branding-topic-125',
  'branding-topic-126',
  'branding-topic-127',
  'branding-topic-128',
  'branding-topic-129',
  'branding-topic-130',
  'branding-topic-131',
  'branding-topic-132',
  'branding-topic-133',
  'branding-topic-134',
  'branding-topic-135',
  'branding-topic-136',
  'branding-topic-137',
  'branding-topic-138',
  'branding-topic-139',
  'branding-topic-140',
  'branding-topic-141',
  'branding-topic-142',
  'branding-topic-143',
  'branding-topic-144',
  
  // Video & Photography (145-168)
  'video-topic-145',
  'video-topic-146',
  'video-topic-147',
  'video-topic-148',
  'video-topic-149',
  'video-topic-150',
  'video-topic-151',
  'video-topic-152',
  'video-topic-153',
  'video-topic-154',
  'video-topic-155',
  'video-topic-156',
  'video-topic-157',
  'video-topic-158',
  'video-topic-159',
  'video-topic-160',
  'video-topic-161',
  'video-topic-162',
  'video-topic-163',
  'video-topic-164',
  'video-topic-165',
  'video-topic-166',
  'video-topic-167',
  'video-topic-168',
  
  // Email Marketing (169-192)
  'email-marketing-topic-169',
  'email-marketing-topic-170',
  'email-marketing-topic-171',
  'email-marketing-topic-172',
  'email-marketing-topic-173',
  'email-marketing-topic-174',
  'email-marketing-topic-175',
  'email-marketing-topic-176',
  'email-marketing-topic-177',
  'email-marketing-topic-178',
  'email-marketing-topic-179',
  'email-marketing-topic-180',
  'email-marketing-topic-181',
  'email-marketing-topic-182',
  'email-marketing-topic-183',
  'email-marketing-topic-184',
  'email-marketing-topic-185',
  'email-marketing-topic-186',
  'email-marketing-topic-187',
  'email-marketing-topic-188',
  'email-marketing-topic-189',
  'email-marketing-topic-190',
  'email-marketing-topic-191',
  'email-marketing-topic-192',
  
  // E-Commerce Marketing (193-216)
  'ecommerce-topic-193',
  'ecommerce-topic-194',
  'ecommerce-topic-195',
  'ecommerce-topic-196',
  'ecommerce-topic-197',
  'ecommerce-topic-198',
  'ecommerce-topic-199',
  'ecommerce-topic-200',
  'ecommerce-topic-201',
  'ecommerce-topic-202',
  'ecommerce-topic-203',
  'ecommerce-topic-204',
  'ecommerce-topic-205',
  'ecommerce-topic-206',
  'ecommerce-topic-207',
  'ecommerce-topic-208',
  'ecommerce-topic-209',
  'ecommerce-topic-210',
  'ecommerce-topic-211',
  'ecommerce-topic-212',
  'ecommerce-topic-213',
  'ecommerce-topic-214',
  'ecommerce-topic-215',
  'ecommerce-topic-216',
  
  // Legal & Compliance (217-224)
  'legal-topic-217',
  'legal-topic-218',
  'legal-topic-219',
  'legal-topic-220',
  'legal-topic-221',
  'legal-topic-222',
  'legal-topic-223',
  'legal-topic-224',
];

// Static pages
export const staticPages = [
  { path: '/', priority: 1.0, changefreq: 'daily' },
  { path: '/about', priority: 0.9, changefreq: 'monthly' },
  { path: '/services', priority: 0.9, changefreq: 'weekly' },
  { path: '/industries', priority: 0.9, changefreq: 'weekly' },
  { path: '/blogs', priority: 0.9, changefreq: 'daily' },
  { path: '/faqs', priority: 0.7, changefreq: 'monthly' },
  { path: '/contact', priority: 0.8, changefreq: 'monthly' },
];

// Generate all URLs
export const getAllUrls = () => {
  const baseUrl = 'https://inchtomilez.com'; // Replace with your actual domain
  
  const urls: { loc: string; priority: number; changefreq: string; lastmod?: string }[] = [];
  
  // Static pages
  staticPages.forEach(page => {
    urls.push({
      loc: `${baseUrl}${page.path}`,
      priority: page.priority,
      changefreq: page.changefreq,
      lastmod: new Date().toISOString().split('T')[0],
    });
  });
  
  // Service pages
  serviceSlugs.forEach(slug => {
    urls.push({
      loc: `${baseUrl}/services/${slug}`,
      priority: 0.8,
      changefreq: 'monthly',
      lastmod: new Date().toISOString().split('T')[0],
    });
  });
  
  // Industry pages
  industrySlugs.forEach(slug => {
    urls.push({
      loc: `${baseUrl}/industries/${slug}`,
      priority: 0.8,
      changefreq: 'monthly',
      lastmod: new Date().toISOString().split('T')[0],
    });
  });
  
  // Blog pages
  blogSlugs.forEach(slug => {
    urls.push({
      loc: `${baseUrl}/blogs/${slug}`,
      priority: 0.7,
      changefreq: 'weekly',
      lastmod: new Date().toISOString().split('T')[0],
    });
  });
  
  return urls;
};
